base:
  save_dir: data/
  # if save_dir exists
  # continue: true -> continue simulation
  # continue: false -> start from scratch
  continue: true

time:
  time_save_dir: time/
  n_output_digits: 8
  tend: 0.8
  dt_output: 0.01

grid:
  i_size: 128
  j_size: 128
  k_size: 1
  margin: 2
  x_min: 0.0
  x_max: 1.0
  y_min: 0.0
  y_max: 1.0
  z_min: 0.0
  z_max: 1.0

mpi:
  mpi_save_dir: mpi/
  x_procs: 2
  y_procs: 1
  z_procs: 1

domain:
  periodic:
    x: true
    y: true
    z: true

mhd:
  mhd_save_dir: mhd/
  n_output_digits: 8
  cfl_number: 1.0
  artificial_viscosity:
    ep: 1.5
    fh: 1.0
    # for characteristic velocity
    cs_fac: 0.8
    ca_fac: 0.8
    vv_fac: 0.8

eos:
  gm: 1.6666666666666667
