io:
  save_dir: ../data_z/
  continue: false

time:
  tend: 0.2
  dt_output: 0.01

grid:
  i_size: 1
  j_size: 1
  k_size: 512
  margin: 2
  x_min: 0.0
  x_max: 1.0
  y_min: 0.0
  y_max: 1.0
  z_min: 0.0
  z_max: 1.0

mpi:
  x_procs: 1
  y_procs: 1
  z_procs: 1

domain:
  periodic:
    x: false
    y: false
    z: false

mhd:

eos:
  gm: 2.0


shock_tube:
  bm: 0.75
  rol: 1.0
  prl: 1.0
  vvl: 0.0
  bpl: 1.0
  ror: 0.125
  prr: 0.1
  vvr: 0.0
  bpr: -1.0
