base:
  save_dir: data/
  # if save_dir exiests
  # continue: true -> continue simulation
  # continue: false -> start from scratch
  continue: true

time:
  time_save_dir: time/
  tend: 20.0
  dt_output: 0.2
  n_output_digits: 8

grid:
  i_size: 384
  j_size: 1152
  k_size: 1
  margin: 2
  xmin: -0.25
  xmax:  0.25
  ymin: -0.75
  ymax:  0.75
  zmin: -0.25
  zmax:  0.25

mpi:
  mpi_save_dir: mpi/
  n_procs_digits: 8
  x_procs: 1
  y_procs: 2
  z_procs: 1

mhd:
  mhd_save_dir: mhd/

eos:
  gm: 1.4

time_integrator:
  cfl_number: 0.5

artificial_viscosity:
  ep: 2.0
  fh: 2.0
  # for characteristic velocity
  cs_fac: 0.5
  ca_fac: 1.0
  vv_fac: 1.0
boundary_condition:
  # please use "standard" or "custom" for boundary_type
  boundary_type: standard

  periodic:
    x: true
    y: false
    z: true

  ro:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  vx:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  vy:
    x: [symmetric, symmetric]
    y: [antisymmetric, antisymmetric]
    z: [symmetric, symmetric]

  vz:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  bx:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  by:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  bz:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  ei:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]

  ph:
    x: [symmetric, symmetric]
    y: [symmetric, symmetric]
    z: [symmetric, symmetric]
