base:
  save_dir: data/
  continue: false

physics:
  rt: true

time:
  time_save_dir: time/
  n_output_digits: 8
  tend: 1.0
  dt_output: 1.0

grid:
  i_size: 64
  j_size: 64
  k_size: 1
  margin: 2
  x_min: -0.5
  x_max: 0.5
  y_min: -0.5
  y_max: 0.5
  z_min: -0.5
  z_max: 0.5

mpi:
  mpi_save_dir: mpi/
  x_procs: 1
  y_procs: 1
  z_procs: 1

domain:
  periodic:
    x: false
    y: true
    z: true

rt:
  num_rays: 24
  tolerance: 1.0e-5
  max_iters: 100
  save_dir: rt/

searchlight:
  abs_coeff: 1.0
  src_func: 0.5
  incoming_intensity: 1.0
  radius: 0.2
