base:
  save_dir: data/
  # if save_dir exists
  # continue: true -> continue simulation
  # continue: false -> start from scratch
  continue: false

time:
  time_save_dir: time/
  tend: 15000.0
  dt_output: 100.0
  n_output_digits: 8

grid:
  i_size: 128
  j_size: 128
  k_size: 128
  margin: 2
  xmin: -44.8
  xmax:  44.8
  ymin: -44.8
  ymax:  44.8
  zmin: -44.8
  zmax:  44.8

mpi:
  mpi_save_dir: mpi/
  n_procs_digits: 8
  x_procs: 2
  y_procs: 1
  z_procs: 1

mhd:
  mhd_save_dir: mhd/

eos:
  gm: 1.6666666666666667

time_integrator:
  cfl_number: 0.3

artificial_viscosity:
  ep: 1.2
  fh: 1.0
  # for characteristic velocity
  cs_fac: 1.0
  ca_fac: 0.8
  vv_fac: 1.0

boundary_condition:
  periodic:
    x: false
    y: false
    z: false

solar_wind: # solar wind parameter at x = xmin boundary
  mass_density: 5.e-4
  gas_pressure: 3.56e-8
  x_velocity_field: 0.05
  z_magnetic_field: -1.5e-4

magnetosphere:
  gas_pressure: 5.4e-7
  radius: 3.5
  a0: 100.0
  gravitational_acceleration: 1.35e-6

floor:
  ro_floor: 1.e-8
  pr_floor: 1.e-10

