name: Formatter

on: [push]

jobs:
  run-cpu-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format C++ code (includes .cu/.cuh)
        run: find . -name "*.cpp" -o -name "*.hpp" -o -name "*.cu" -o -name "*.cuh" | xargs clang-format -i
