name: Run tests on CPU

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nlohmann-json3-dev libyaml-cpp-dev
          sudo apt-get install -y libopenmpi-dev openmpi-bin
      - name: Generate build directory
        run: |
          cmake -B build -S . -DUSE_CUDA=OFF
      - name: Build unit tests
        working-directory: build
        run: make unit_test
      - name: Run unit tests
        run: ./unit_test

