name: Run tests on CPU

on: [push]

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install clang-format
          clang-format --version
      - name: Check format
        run: find src include problems tests -name "*.cpp" -o -name "*.hpp" -o -name "*.cu" -o -name "*.cuh" | xargs clang-format --dry-run --Werror -fallback-style=none
  run-cpu-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-cpp-dev libopenmpi-dev openmpi-bin
      - name: Generate build directory
        run: |
          cmake -B build -S miso -DMISO_USE_CUDA=OFF
          cmake --build build -j
      - name: Run unit tests
        working-directory: build
        run: |
          OMPI_MCA_btl_vader_single_copy_mechanism=none \
          OMPI_MCA_rmaps_base_oversubscribe=yes \
          pwd\
          ctest -V -j
      - name: Build demo
        working-directory: demo/mhd2d_vortex
        run: |
          cmake -B build -S . -DUSE_CUDA=OFF
          cmake --build build -j
